### ISSUE TITLE
CSRF checking fails for /admin

### ISSUE THREAD

**Issue by pamelafox** [github/codespaces-django#7]
CSRF checking currently fails when trying to login to admin.
<img width="1239" alt="Screenshot 2022-11-16 at 3 26 37 PM" src="https://user-images.githubusercontent.com/297042/202317127-c01601d2-5a9a-4020-b51c-2e75ceb294e9.png">

I fixed that this morning in my own Django Codespace-optimized repo. You can see how I fixed that here:
https://github.com/Azure-Samples/msdocs-django-postgresql-sample-app/pull/19/files

I'm happy to send a PR if you'd like.

**Comment by bdmac** [comment]
I don't think we even realized there _was_ an admin for this (we don't really do much Django work as you can imagine). Would love a PR for it if you have time!

**Comment by pamelafox** [comment]
Ah, Django's big selling point is its ORM and auto-generated admin for it, so yup, it's a good thing to get working. I've made the PR at https://github.com/github/codespaces-django/pull/8
Unfortunately, it won't work in the embedded browser window thats configured for this Codespace, since that seems to disable cookies, but will work in a proper external window.

**Comment by pamelafox** [comment]
Fixed via #8

**Comment by deepskydata** [comment]
Sorry to open this up again. I have a similar issue even with the fix. I tried it in an external browser but still got the origin error. CSFR token is sent with the request. 

Should I open a new issue?

**Comment by ethanolj** [comment]
@deepskydata - I just troubleshooted the same, after creating a new Django project using `django-admin startproject`. I opened #24 for this issue, however the #8 fix can be applied in the new project's settings.py file manually as a work-around.
